language: rust
install:
  - sudo apt-add-repository ppa:andrewrk/libgroove -y
  - sudo apt-get update
  - sudo apt-get install libgroove-dev
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
notifications:
  email:
    on_success: never
