language: rust
install:
  - sudo apt-add-repository ppa:andrewrk/libgroove -y
  - sudo apt-get update
  - sudo apt-get install libgroove-dev
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
notifications:
  email:
    on_success: never
env:
  global:
    - secure: fABMIt5khhYF0qMguxyk927BFBPQ54ykLGVYASuHk23uFeR8FYCFyBkt0Pw4CkZI+VB4W8ipTjmn9VTDcxzLw+qBezGX4hoe/nJjKu1EkOypKhP79U//Bp0cb4uckgTGL+lojnuoZWCnchfzHT6kmamW0UthDq9lSSwacMMxuuM=
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
