language: rust
install:
  sudo apt-add-repository -y ppa:andrewrk/libgroove
  sudo apt-get update
  sudo apt-get install libgroove-dev
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
notifications:
  email:
    on_success: never
